Rename directory from wic to files to clear an error.
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:
    wic/wks files at /builds/balister/sdr-build/openembedded-core/../meta-sdr/wic need to be moved to files/wic within the layer to be found/used
wic/wks files at /builds/balister/sdr-build/openembedded-core/../meta-sdr/wic need to be moved to files/wic within the layer to be found/used

Signed-off-by: Philip Balister <philip@balister.org>